name: termitty
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  xterm: ^3.4.1

  dartssh2: ^2.5.0

  flutter_pty: ^0.3.0

  flutter_acrylic: ^1.0.0+2

  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.3

  after_layout: ^1.1.0
  dart_openai: ^1.9.92
  flutter_dotenv: ^5.0.2
  flutter_gpt_tokenizer: ^0.1.0
  tuple: ^2.0.1
  syncfusion_flutter_charts: ^21.2.4
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0

  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png 
    - assets/.env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Cascadia Mono
      fonts:
        - asset: fonts/CascadiaMonoPL.ttf
